### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by foxslot** [foxslot/JS_HW09_LoadingPostsFrontend#1]
Прошу проверить ДЗ
ссылка на веб сервер https://github.com/foxslot/JS_HW09_LoadingPostsBackend/blob/master/app.js
ссылка git hub pages https://foxslot.github.io/JS_HW09_LoadingPostsFrontend/

**Comment by coursar** [comment]
Всё ок, возможности улучшения: запускать setInterval только после первого получения постов - посмотрите как оно работает, когда Heroku "убил" ваше приложение.
